### PR TITLE
Add results for current panama-vector build

### PR DESCRIPTION
**Pull request by amCap1712**
I ran the benchmarks on the latest build of panama-vector repo available at builds.shipilev.net. Here are the results in csv as well,
https://gist.github.com/amCap1712/92d1d34a724939a2daf45eb2e7bfc6a9

It seems that the performance has markedly improved since March. The one case which suffers the most is ASCII only one. I ran the perfasm profiler with JMH and see that no vector instructions were generated for it :(.

I also did some experimenting with using static finals instead. Its a WIP, it boosts perfomance significantly at the cost of not letting the user choose the Vector size. Will open a PR for it shortly.

### CODE REVIEW

**Comment by lemire** [comment]
+1

**Comment by AugustNagro** [comment]
Thanks, it's great to see they are making progress.

I merged your changes & will run the benchmarks on my desktop.

**Comment by AugustNagro** [comment]
Please checkout the updated readme! https://github.com/AugustNagro/utf8.java#performance

Performance is a lot better now. I also updated the lookup tables to be both fast and configurable (for example [LookupTables256](https://github.com/AugustNagro/utf8.java/blob/master/src/main/java/com/augustnagro/utf8/LookupTables256.java)). There was no significant difference from using an interface delegating to static fields vs hard-coding static fields.

The JIT will inline dynamic dispatch for up to 2 implementations, so I made sure to split each benchmark into its own class to ensure only the relevant LookupTables class was classloaded on each JVM fork.

**Comment by amCap1712** [comment]
Thanks @AugustNagro. I was also going to test a similar LookupTables approach next but I already like your version better :D. Cheers!

**Comment by amCap1712** [comment]
@AugustNagro Regarding JIT inlining, as mentioned [here](https://shipilev.net/blog/2015/black-magic-method-dispatch/#_monomorphic_cases) it is per call site. (I consider the benchmark method as the call site not Utf8.validate because JMH runs with don't inline the benchmark body compiler hint. Also, each benchmark method is run its own fork so Utf8.validate would observe only one implementation anyways.).  Since each benchmark will always observe the same implementation, all call sites in the benchmark body are monomorphic and JIT inlineable. I tested locally and didn't observe performance difference if all benchmarks are put in the same class. If you desire, I can open a PR to merge the benchmarks into one class.

**Comment by AugustNagro** [comment]
Thanks for checking; please do :)

**Comment by ohpauleez** [comment]
I'm extremely impressed with the effort and results here - well done!  Please keep kicking ass on the road to simdjson!

**Pull request closed without merging**
